name: Publish to PyPI
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Update Release Version From tag
        run: |
          export VERSION=${{ github.event.release.tag_name }}
          python scripts/release_version.py ${VERSION}

      - name: Install and configure Poetry
        run: |
          make poetry_install
          poetry config virtualenvs.create false
      - name: Install requirements
        run: make install
      - name: Build dists
        run: |
          make clean
          make build
          ls dist
      - name: Pypi Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}